version: '3.1'
services:

  mongo:
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=P_ss!98578
    image: mongo:latest
    volumes:
      - $PWD/data:/data/db
    ports:
      - "27017:27017"

  mocker:
    container_name: mocker
    restart: always
    build: .
    ports:
      - "5000:5000"
    links: 
      - mongo

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    links: 
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: P_ss!98578
      ME_CONFIG_MONGODB_URL: mongodb://root:P_ss!98578@mongo:27017/