version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}
    volumes:
      - $PWD/data:/data/db
    ports:
      - ${MONGO_PORT}:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_ROOT}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DB_ROOT}:${MONGO_DB_ROOT_PASSWORD}@mongo:${MONGO_PORT}

  mocker:
    container_name: mocker
    restart: always
    build: .
    ports:
      - ${MOCKER_PORT}:5000
    links:
      - mongo
    depends_on:
      - mongo
